baseURL = "https://iparkirk.github.io/ai_healthcare/"
title = "AI Healthcare"
theme = "hugo-book"

canonifyURLs = true  # Ensure URLs are absolute
relativeURLs = false  # Avoid relative path issues

[params]
  BookTheme = "light"
  BookToC = true
  BookSearch = true


