baseURL = "https://iparkirk.github.io/ai_healthcare/"
title = "AI Healthcare"
theme = "hugo-book"

RelativeURLs=true
CanonifyURLs=true

[params]
  BookTheme = "light"
  BookToC = true
  BookSearch = true


